swagger:
  api:
    contact:
      name: info@puff.codes
      url: https://puff.codes
      email: info@puff.codes
    license:
      name: MIT License
      url: https://opensource.org/licenses/MIT