spring:
  data.web.pageable:
    default-page-size: 20
    max-page-size: 100
  h2:
    enabled: false
    console:
      enabled: false
  datasource:
    url: ${MYSQL_JDBC_CONNECTION_STRING}
    username: ${SQL_DB_USERNAME}
    password: ${SQL_DB_PASSWORD}
    driverClassName: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
    show-sql: true